### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by vap999793** [aw1875/puppeteer-hcaptcha#43] opened 2022-02-03 13:06 UTC
Hi,

`npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\VISHAL ANAND\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\VISHAL ANAND\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > ghost-cursor@1.1.7 prepare
npm ERR! > husky install && yarn lint && yarn build
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! .git can't be found (see https://git.io/Jc3F9)
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\VISHAL ANAND\AppData\Local\npm-cache_cacache\tmp\git-cloneKtL5qP
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c husky install && yarn lint && yarn build
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR! C:\Users\VISHAL ANAND\AppData\Local\npm-cache_logs\2022-02-03T08_52_25_351Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\VISHAL ANAND\AppData\Local\npm-cache_logs\2022-02-03T08_51_55_111Z-debug-0.log`

Getting deprecated error but it is also not installing the package. I am getting this error every time.

**Comment by almadrasa** [comment] 2022-02-03 19:37
![image](https://user-images.githubusercontent.com/34221874/152416306-4adf42c2-9dba-481f-b9e1-cc92a86c7d97.png)

same issue

**Comment by sshehab1** [comment] 2022-02-04 15:27
I have the issue

**Comment by sshehab1** [comment] 2022-02-04 15:39
install yarn and try again
`npm install --global yarn`

**Comment by sshehab1** [comment] 2022-02-04 15:59
my issue is with the library related to libtensorflow
[==============================] 1655247/bps 100% 0.0s
* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! install response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/3.13.0/CPU-windows-3.13.0.zip
node-pre-gyp WARN Pre-built binaries not installable for @tensorflow/tfjs-node@3.13.0 and node@12.0.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v4/3.13.0/CPU-windows-3.13.0.zip
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\ProgramData\nvm\v12.0.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.22000

**Comment by almadrasa** [comment] 2022-02-04 17:16
package installed but when trying to require it :
![image](https://user-images.githubusercontent.com/34221874/152573184-5bf8da39-a4ff-4ef5-88b8-2242f8084878.png)

**Comment by vap999793** [comment] 2022-02-05 07:48
> install yarn and try again `npm install --global yarn`

Still not able to install the package after install yarn

**Comment by aw1875** [comment] 2022-02-07 23:50
What version of node are you running? What version of npm are you running/what version of yarn are you running?

**Comment by vap999793** [comment] 2022-02-08 18:20
npm version - 8.3.1
node version - v16.13.1
yarn version  - 1.22.17

**Comment by aw1875** [comment] 2022-02-10 14:42
Let me try on a few different computers and see if I'm having the same issue.

**Comment by Bogdan1001** [comment] 2022-02-11 14:01
> npm version - 8.3.1
> node version - v16.13.1
> yarn version - 1.22.17

I'd the same error all work after I've updated node to 16.14.0,

**Comment by timbru31** [comment] 2022-02-11 17:16
This is being caused because you depend on ghost-cursor git installation vs. the npm release.

**Comment by vap999793** [comment] 2022-02-11 18:07
> > npm version - 8.3.1
> > node version - v16.13.1
> > yarn version - 1.22.17
> 
> I'd the same error all work after I've updated node to 16.14.0,

Still getting the same error

**Comment by Revadike** [comment] 2022-02-14 15:31
> install yarn and try again `npm install --global yarn`

I had the same error, and after this I'm getting:

> npm ERR! npm ERR! code 1
> npm ERR! npm ERR! path C:\Users\Roy\AppData\Local\npm-cache\_cacache\tmp\git-clonejy5Fg4
> npm ERR! npm ERR! command failed
> npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c husky install && yarn lint && yarn build
> npm ERR! npm ERR! fatal: not a git repository (or any of the parent directories): .git
> npm ERR! npm ERR! 'yarn' is not recognized as an internal or external command,
> npm ERR! npm ERR! operable program or batch file.

**Comment by Revadike** [comment] 2022-02-16 04:29
I can confirm that the latest update fixes this issue.

**Comment by aw1875** [comment] 2022-02-16 04:47
I will be closing this issue later today if nobody else still has the issue.

**Comment by vap999793** [comment] 2022-02-16 18:06
I am able to install it but it is not able to solve the captcha, neither I am getting the token.

I have used both the codes to solve the captcha and to get the token

**Comment by Revadike** [comment] 2022-02-16 18:12
both the codes?

**Comment by vap999793** [comment] 2022-02-16 18:43
> both the codes?

to set the response value and to get the token

**Comment by Revadike** [comment] 2022-02-16 22:20
I don't understand your comment

**Comment by aw1875** [comment] 2022-02-16 22:22
I understand. You're saying that you tried both manually returning the response token and automatically setting it and neither work. What website are you trying to work with and have you walked through the code with a debugger to see exactly what is happening?

**Closed** 2022-05-25 17:34 UTC
Labels: question
