### ISSUE TITLE
[Bug]: completed: token returned as undefined

### ISSUE THREAD

**Issue by PYTHON17912** [aw1875/puppeteer-hcaptcha#72] opened 2023-05-06 06:03 UTC
**Describe the bug**

**To Reproduce**
1. Code block(s) with your code.

Example:

```javascript
const { hcaptchaToken } = require('puppeteer-hcaptcha');

(async () => {
    let token = await hcaptchaToken(<URL>);
    console.log(token);
})();
```
2. Description of your files hierarchy (either a photo or markdown).

Example:

```
exampleproject
│
└───node_modules
└───folder
│   │   file.txt
│   │   file2.txt
│   solve.js
```

3. Any other steps needed to reproduce issue.

**Screenshots**

**Errors Received**
If no screenshots available then please send the error received.

**Additional context**

**Comment by aw1875** [comment] 2023-05-06 06:50
You didn't fill out any of the issue template, I have no idea what the context behind the issue is.

**Comment by PYTHON17912** [comment] 2023-05-06 16:24
Please update it 🥺 , coco-ssd is useless now

**Comment by aw1875** [comment] 2023-05-06 16:34
I'm aware that coco-ssd hasn't been working great for some time now. I haven't had any other model recommendations and unfortunately don't have the time to focus on training a decent model for this task. Since you've provided nothing else for me to help you I'm going to close this issue.

**Closed as not planned by aw1875** 2023-05-06 16:34 UTC
Labels: bug
