### ISSUE TITLE
Node js version

### ISSUE THREAD

**Issue by LipeTadeu** [aw1875/puppeteer-hcaptcha#24] opened 2021-12-14 20:42 UTC
Hi, how are you?
What is the best version of node.js to run this project?
I am using this Latest LTS Version: 16.13.1 (includes npm 8.1.2) but it is not going well.
Thanks.

**Comment by aw1875** [comment] 2021-12-14 20:44
I believe I'm on Node v16.5.0 but it shouldn't make a difference. Are you having issues with the project?

**Comment by LipeTadeu** [comment] 2021-12-14 20:59
> Acredito que estou usando o Node v16.5.0, mas isso não deve fazer diferença. Você está tendo problemas com o projeto?

Hi, thanks for the quick reply.
yes i am, it is failing when i use npm i puppeteer-hcaptcha command to install.
It is crashing and generating an error in the installation of tensorflow.
I'm using it on windows.
Thanks.

**Comment by aw1875** [comment] 2021-12-14 21:02
If you want to attach the stack trace I can look into it and see if I can figure out the issue for you

**Comment by LipeTadeu** [comment] 2021-12-14 21:07
> 

Perfect, I want it.
I will process installation caught error for you. print and put here and error messages.
Thank you very much for your availability.

**Comment by LipeTadeu** [comment] 2021-12-14 21:39
> If you want to attach the stack trace I can look into it and see if I can figure out the issue for you

Hello Here is an error generated.
C:\Users\lipet\Desktop\test\puppeteer-hcaptcha\demos>node solve.js
2021-12-14 18:36:32.627727: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

    Puppeteer is missing. :-)

    Note: puppeteer is a peer dependency of puppeteer-extra,
    which means you can install your own preferred version.

    - To get the latest stable version run: 'yarn add puppeteer' or 'npm i puppeteer'

    Alternatively:
    - To get puppeteer without the bundled Chromium browser install 'puppeteer-core'
    - To use puppeteer-firefox install 'puppeteer-firefox' and use the 'addExtra' export

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'puppeteer'
Require stack:
- C:\Users\lipet\node_modules\puppeteer-extra\dist\index.cjs.js
- C:\Users\lipet\Desktop\test\puppeteer-hcaptcha\demos\solve.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireVanillaPuppeteer (C:\Users\lipet\node_modules\puppeteer-extra\dist\index.cjs.js:457:17)
    at C:\Users\lipet\node_modules\puppeteer-extra\dist\index.cjs.js:420:34
    at Object.<anonymous> (C:\Users\lipet\node_modules\puppeteer-extra\dist\index.cjs.js:421:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\lipet\\node_modules\\puppeteer-extra\\dist\\index.cjs.js',
    'C:\\Users\\lipet\\Desktop\\test\\puppeteer-hcaptcha\\demos\\solve.js'
  ]
}[
![erro](https://user-images.githubusercontent.com/26200412/146083501-6a71f4ee-0c4d-42e2-993d-8d9b48f14677.png)
](url)

**Comment by LipeTadeu** [comment] 2021-12-14 22:08
> If you want to attach the stack trace I can look into it and see if I can figure out the issue for you

Hello Now you can install ok.
Everything feels right.
the only problem now is this.

2021-12-14 19:04:01.925462: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following instructions CPU in performance-critical operations: AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

It opens the browser but it doesn't solve the captcha. I'm using your solve.js demo script

**Comment by aw1875** [comment] 2021-12-14 23:07
The tensorflow warning is a known issue, see [here](https://github.com/aw1875/puppeteer-hcaptcha/blob/master/README.md#known-issues). It doesn't have any real effect on the process so it should be fine. The demo page doesn't actually press the submit button once completed, did you make sure you're doing that?

**Comment by LipeTadeu** [comment] 2021-12-15 00:21
> The tensorflow warning is a known issue, see [here](https://github.com/aw1875/puppeteer-hcaptcha/blob/master/README.md#known-issues). It doesn't have any real effect on the process so it should be fine. The demo page doesn't actually press the submit button once completed, did you make sure you're doing that?

So I processed the token return script, but it didn't print the response either.
Shouldn't it print the token?

**Comment by aw1875** [comment] 2021-12-15 00:48
You mind sharing your project structure and code?

**Comment by LipeTadeu** [comment] 2021-12-15 01:09
> You mind sharing your project structure and code?

Not even.
I'm running your example script which returns token.

// Require our hcaptchaToken method
const { hcaptchaToken } = require('puppeteer-hcaptcha');

(async() => {
  // Create Start Time
  const startTime = Date.now();

  // Call hcaptchaToken method passing in your url
  let token = await hcaptchaToken('https://2captcha.com/demo/hcaptcha');

  // Get End Time
  const endTime = Date.now();

  // Log timed result to console
  console.log(`Completed in ${(endTime - startTime) / 1000} seconds`);

  // P0_eyJ0eXAiOiJ...
  console.log(token);
})();

**Comment by LipeTadeu** [comment] 2021-12-15 12:11
> Interesting. I can't see any reason it wouldn't be working with the demo code as I tested it many times on multiple different platforms. Only thing I can suggest is setting a breakpoint and walking through the code with the debugger to see where the issue resides. I just did another test right now and it had no issues:
> 
> ```
> Completed in 18.982 seconds
> P0_eyJ0eXAiOiJKV...
> ```

Strange indeed, but it really won't. I'm in Brazil, I don't know if this has anything to do with it.
anyway thank you very much for your availability to help me, your project is very cool.

**Comment by aw1875** [comment] 2021-12-16 02:18
> > Interesting. I can't see any reason it wouldn't be working with the demo code as I tested it many times on multiple different platforms. Only thing I can suggest is setting a breakpoint and walking through the code with the debugger to see where the issue resides. I just did another test right now and it had no issues:
> > ```
> > Completed in 18.982 seconds
> > P0_eyJ0eXAiOiJKV...
> > ```
> 
> Strange indeed, but it really won't. I'm in Brazil, I don't know if this has anything to do with it. anyway thank you very much for your availability to help me, your project is very cool.

Appreciate it! I wish I could be more helpful but I'm not entirely sure what the issue is unfortunately.

**Comment by LipeTadeu** [comment] 2021-12-16 13:35
> > > Interesting. I can't see any reason it wouldn't be working with the demo code as I tested it many times on multiple different platforms. Only thing I can suggest is setting a breakpoint and walking through the code with the debugger to see where the issue resides. I just did another test right now and it had no issues:
> > > ```
> > > Completed in 18.982 seconds
> > > P0_eyJ0eXAiOiJKV...
> > > ```
> > 
> > 
> > Strange indeed, but it really won't. I'm in Brazil, I don't know if this has anything to do with it. anyway thank you very much for your availability to help me, your project is very cool.
> 
> Appreciate it! I wish I could be more helpful but I'm not entirely sure what the issue is unfortunately.

Hi, I appreciate it.
Just one more question, would you have and would it be possible to send me the project that used Google Vision?
It could be a link to download or something like that, I don't know if it's on file.
Or email me.
Thanks.

**Comment by aw1875** [comment] 2021-12-18 03:59
@LipeTadeu I'll try to make a new branch with all the updated code using Google Vision in the next few days just been a little busy unfortunately.

**Comment by LipeTadeu** [comment] 2021-12-18 14:51
> @LipeTadeu I'll try to make a new branch with all the updated code using Google Vision in the next few days just been a little busy unfortunately.

thank you so much. I'm waiting.

**Comment by aw1875** [comment] 2021-12-23 19:05
@LipeTadeu sorry for the wait. Google Cloud Vision version has been pushed to the branch [GoogleCloudVision](https://github.com/aw1875/puppeteer-hcaptcha/tree/GoogleCloudVision). It won't be packaged as a node module but you can still clone the code and run it if you'd like to. I will be closing this issue now but you can reopen it if you really need to.

**Closed by aw1875** 2021-12-23 19:05 UTC
Labels: question
