### ISSUE TITLE
Still same token not working issue

### ISSUE THREAD

**Issue by byOsta** [aw1875/puppeteer-hcaptcha#6] opened 2021-04-23 11:18 UTC
On the mentioned webpage with this new changes It's still not working. I've been testing to try to understand a little more about this. 

I've seen that the "hsl", "hsw", "hsj", changes when the `userAgent` is changing. 
So, when I load the page on my chrome normally, this first call (https://hcaptcha.com/checksiteconfig) It's always "hsw" but with this package, the response is "hsl" almost every time. 
If you put the user agent for example to something like `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_0) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/90 Safari/537.4` on the `userAgent` header you will get "hsw"

Another thing that I've seen it's that in this page the `origin` header in this first call is https://newassets.hcaptcha.com instead of 'https://assets.hcaptcha.com'
And the hsw that it's using is : https://newassets.hcaptcha.com/c/36c79c31/hsw.js (Yesterday I remember that it was different)
Even if you force the value in chrome to use this userAgent that it's getting the "hsl" value the hsl.js url it's different (https://newassets.hcaptcha.com/c/36c79c31/hsl.js)

I think that this change made that you get this first `pass` value on the first `checksiteconfig` it's not returning a valid token to use it, it's a JSON Web Token that I don't really know what it's used for. Atleast with the other changes it returned something that looked like a token `F0_eyJ0eXAiOiJ...` but that didn't worked either

**Comment by aw1875** [comment] 2021-04-23 14:51
My apologies, I guess I was very tired yesterday as the code I pushed doesn't actually do anything and is what is supposed to happen. I am going to take a look at it now as I am able to get the correct response token so I want to check through the requests now as you talked about above.
![image](https://user-images.githubusercontent.com/36057494/115889263-ca4f4200-a421-11eb-8c6d-f72358baccd1.png)

**Comment by aw1875** [comment] 2021-04-23 21:49
Alright I believe I found where the issue is coming from. I need to look through the requests to make sure I can find a solution to the problem and then I can hopefully push a fix in the next few hours.

**Comment by aw1875** [comment] 2021-04-23 23:06
@byOsta I have pushed a temporary fix for HSJ requests. Both HSW and HSL requests worked with no issues for me. From what I understand it looks like hCaptcha uses HSJ only for certain browser user agents. The error that you were getting was because while sending the request to get all the images using HSJ the response was returning a `fail` rather than `pass` so I was not getting any tasks. I'm working on a more permanent solution as I was able to tweak the code to get those tasks using HSJ, however it seems like the request for checking answers is different as well so I need to figure that out before I can push the permanent solution. I am once again going to close this issue but if the problem still persists just reopen this issue and I can see what the problem is.

**Closed by aw1875** 2021-04-23 23:06 UTC
