### ISSUE TITLE
[Question]: Is it still alive ?

### ISSUE THREAD

**Issue by dadodasyra** [aw1875/puppeteer-hcaptcha#61] opened 2022-06-16 13:47 UTC
I'm currently trying to use the extension has showed in the ReadMe (with the autofill). It seems to partially work, like 1 on 4 times. I saw that sometimes the token returned is undefined.
So I tried to debug it a little bit and found that there was an error 400 Bad request. And in this case the code doesnt seems to try to retry the captcha complete but return an undefined token
```
StatusCodeError: 400 - {"c":{"type":"hsw","req":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmIjowLCJzIjoxNiwidCI6InciLCJkIjoiTFdvZmxoQmRsZE0xSVZibzhyNjN2V29rWG9jM042RGdVQlhzMTI5WlQ1QUd4NWlCcklyMTFpaG5hSWMzbG5TcktVd0pUZFlQOE5TZUoxUzY
5cU8rQXArSlNjZzlNcVVCbU84MHZmL01yeXNOS2ZtOHJvcEt5ak4xbkR6N0VKcERlWVNTdzJkSGhpUGY4dVBqLzFyaUNESDBFV2pLaGtsR2pVK0FueTQ2eUxtR2dzamJpT29qR0oxM2FqUT1POGRIYWpTbnBVQmZFT0VVIiwibCI6Imh0dHBzOi8vbmV3YXNzZXRzLmhjYXB0Y2hhLmNvbS9jLzUwYWM2NTY4
IiwiZSI6MTY1NTM4MTYzNX0.2QksjzqSupZBHq4yX9-dPP-pm0zXXzr7tIubKsY-L90"},"pass":false,"error":"invalid"}
```

**Comment by dadodasyra** [comment] 2022-06-16 14:14
After more digging I found that it freeze on `https://hcaptcha.com/checkcaptcha/${key}?s=${sitekey}` https://github.com/aw1875/puppeteer-hcaptcha/blob/master/hcaptcha.js#L285

**Comment by dadodasyra** [comment] 2022-06-16 14:17
And the error is catched here https://github.com/aw1875/puppeteer-hcaptcha/blob/master/hcaptcha.js#L285. Maybe we should trigger a retry, and at least search a little bit why we're getting a 400 bad request

**Comment by dadodasyra** [comment] 2022-06-16 14:21
And btw some times the waitForSelector line 347 some times just get stuck, even if the captcha is loaded

**Comment by aw1875** [comment] 2022-06-17 02:18
I've been quite busy so haven't really taken a look at hCaptcha but after a quick inspection of the code it looks like the issue is related to the TensorFlow model not correctly identifying the images. Right now the entire answer block comes back as false every time I run the code. So, when I have a little more free time I'll try to dive into that and see exactly what is happening there.

**Comment by aw1875** [comment] 2022-06-23 06:34
@dadodasyra Ran some more tests today and it looks like they seem to be passing now. Not sure if there is really anything I can do aside from training my own model or finding a better source for the image recognition. I'm going to close this issue now but if you have any alternative solutions for the image recognition please let me know.

**Closed** 2022-06-23 06:34 UTC
Labels: question
